spring:
  application:
    name: luooj-backend-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: luooj-backend-user-service
          uri: lb://luooj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: luooj-backend-question-service
          uri: lb://luooj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: luooj-backend-judge-service
          uri: lb://luooj-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: luooj-backend-file-service
          uri: lb://luooj-backend-file-service
          predicates:
            - Path=/api/file/**
  main:
    web-application-type: reactive

server:
  port: 8504

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
# 这个配置是不用看token是否合法 直接通过
gateway:
  excludedUrls: /api/user/get/login,/api/user/logout,/api/user/login,/api/user/register,/api/question/list/page/vo,/api/file,/doc.html,/api/user/doc.html,/api/question/doc.html,/api/judge/doc.html